# Generated by Django 4.2.30 on 2026-07-02 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('NB', 'NB'), ('NL', 'NL'), ('NS', 'NS'), ('NT', 'NT'), ('NU', 'NU'), ('ON', 'ON'), ('PE', 'PE'), ('QC', 'QC'), ('SK', 'SK'), ('YT', 'YT')], max_length=2)),
                ('postal_code', models.CharField(max_length=7)),
                ('country', models.CharField(default='Canada', max_length=80)),
                ('billing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('bi_monthly', 'Bi Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('typical_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_day', models.PositiveSmallIntegerField(default=1)),
                ('auto_pay', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider__name', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('natural_gas', 'Natural gas'), ('water', 'Water'), ('internet', 'Internet'), ('mobile', 'Mobile phone'), ('home_phone', 'Home phone'), ('tv', 'TV/cable'), ('insurance', 'Insurance'), ('property_tax', 'Property tax'), ('mortgage_rent', 'Mortgage/rent'), ('condo_fees', 'Condo/maintenance fees'), ('credit_card', 'Credit cards'), ('loan', 'Loans'), ('subscription', 'Subscriptions'), ('other', 'Other')], max_length=30)),
                ('website_url', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('province_region', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False, editable=False)),
                ('is_custom', models.BooleanField(default=True, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.PositiveSmallIntegerField()),
                ('billing_year', models.PositiveSmallIntegerField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit', 'Debit'), ('auto_pay', 'Auto Pay'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tracker.billaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-billing_year', '-billing_month', 'due_date'],
            },
        ),
        migrations.AddField(
            model_name='billaccount',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='tracker.provider'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tracker.models.attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tracker.billpayment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_custom_provider_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='billpayment',
            constraint=models.UniqueConstraint(fields=('bill_account', 'billing_month', 'billing_year'), name='unique_account_billing_period'),
        ),
    ]
