# Generated by Django 5.2.18 on 2026-10-07 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='period_end',
            field=models.DateField(blank=True, help_text='Last day of the service period.', null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='period_start',
            field=models.DateField(blank=True, help_text='First day of the service period.', null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='statement_date',
            field=models.DateField(blank=True, help_text='The date printed on the bill.', null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='usage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumption shown on the bill.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='usage_unit',
            field=models.CharField(blank=True, choices=[('kWh', 'kWh'), ('m³', 'm³')], max_length=10),
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='province',
            field=models.CharField(blank=True, choices=[('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('NB', 'NB'), ('NL', 'NL'), ('NS', 'NS'), ('NT', 'NT'), ('NU', 'NU'), ('ON', 'ON'), ('PE', 'PE'), ('QC', 'QC'), ('SK', 'SK'), ('YT', 'YT')], max_length=2),
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='service_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, help_text='New charges on this bill.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid')], default='unpaid', editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short name, such as the street address or “Cottage”.', max_length=100)),
                ('ownership', models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented')], max_length=10)),
                ('street_address', models.CharField(help_text='Include the unit, for example “52 De Grassi St, Unit 1”.', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('NB', 'NB'), ('NL', 'NL'), ('NS', 'NS'), ('NT', 'NT'), ('NU', 'NU'), ('ON', 'ON'), ('PE', 'PE'), ('QC', 'QC'), ('SK', 'SK'), ('YT', 'YT')], max_length=2)),
                ('postal_code', models.CharField(max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='billaccount',
            name='property',
            field=models.ForeignKey(blank=True, help_text='The address fields below are filled from the property when left blank.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='tracker.property'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_property_owner_name'),
        ),
    ]
