# Generated by Django 5.2.18 on 2026-10-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_derive_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='needs_review',
            field=models.BooleanField(default=False, editable=False, help_text='Read by the general bill reader and not checked yet.'),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='usage_unit',
            field=models.CharField(blank=True, choices=[('kWh', 'kWh'), ('m³', 'm³'), ('gal', 'gal')], max_length=10),
        ),
    ]
